openapi: 3.0.2
info:
  title: Test
  version: 0.1.0
servers:
  - url: http://localhost
paths:
  /:
    get:
      operationId: sample
      parameters:
        - name: name
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Animal'
      responses:
        200:
          description: test
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal'
components:
  schemas:
    Animal:
      properties:
        name:
          type: string
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: type
        mapping:
          cat: '#/components/schemas/Cat'
          dog: '#/components/schemas/Dog'
    Dog:
      properties:
        type:
          type: string
        weight:
          type: integer
          minimum: 0
          maximum: 100
        barksPerMinute:
          type: integer
    Cat:
      properties:
        type:
          type: string
        weight:
          type: integer
          minimum: 0
          maximum: 100
        meowsPerMinute:
          type: integer